version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
volumes:
  postgres-data:
    external: false
  redis-data:
    external: false
