version: '3.8'
services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    volumes:
      - .docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
