server:
  port: 8080
  shutdown: graceful
spring:
  main:
    banner-mode: off
    lazy-initialization: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      repositories:
        enabled: false
    jpa:
      repositories:
        bootstrap-mode: deferred
  aop:
    auto: false
  jmx:
    enabled: false
  jta:
    enabled: true
  servlet:
    multipart:
      enabled: false
  dao:
    exceptiontranslation:
      enabled: false
  application:
    admin:
      enabled: false
  sql:
    init:
      mode: never
  mvc:
    formcontent:
      filter:
        enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.integration.IntegrationAutoConfiguration
      - org.springframework.boot.autoconfigure.ssl.SslAutoConfiguration
      - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
      - org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration
      - org.springframework.boot.autoconfigure.netty.NettyAutoConfiguration
      - org.springframework.boot.autoconfigure.reactor.ReactorAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration
      - org.springframework.boot.autoconfigure.web.client.RestClientAutoConfiguration
      - org.springframework.boot.autoconfigure.web.client.RestTemplateAutoConfiguration
      - org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration
      - org.springframework.boot.autoconfigure.task.TaskSchedulingAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.observation.web.client.HttpClientObservationsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.endpoint.jmx.JmxEndpointAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.observation.ObservationAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.scheduling.ScheduledTasksObservabilityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.integration.IntegrationMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.CompositeMeterRegistryAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.jdbc.DataSourcePoolMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.JvmMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.LogbackMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.export.simple.SimpleMetricsExportAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.startup.StartupTimeMetricsListenerAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.task.TaskExecutorMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.web.tomcat.TomcatMetricsAutoConfiguration
management:
  endpoints:
    jmx:
      exposure:
        exclude: '*'
    web:
      exposure:
        include: health
      base-path: '/'
  health:
    diskspace:
      enabled: false
