spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/rinha
  data:
    redis:
      host: localhost
      port: 6379